const recipes = [
  {
    id: 1,
    name: "Spaghetti Bolognese",
    ingredients: [
      "Spaghetti",
      "ground beef",
      "tomatoes",
      "onions",
      "garlic",
      "red wine",
      "salt",
      "pepper",
      "olive oil",
    ],
    price: 15.0,
  },
  {
    id: 2,
    name: "Lasagna",
    ingredients: [
      "Lasagna noodles",
      "ground beef",
      "tomato sauce",
      "mozzarella cheese",
      "parmesan cheese",
      "salt",
      "pepper",
      "olive oil",
    ],
    price: 20.0,
  },
  {
    id: 3,
    name: "Pizza Margherita",
    ingredients: [
      "Pizza dough",
      "tomatoes",
      "mozzarella cheese",
      "basil",
      "salt",
      "pepper",
      "olive oil",
    ],
    price: 12.0,
  },
  {
    id: 4,
    name: "Chicken Parmesan",
    ingredients: [
      "Chicken breasts",
      "breadcrumbs",
      "parmesan cheese",
      "mozzarella cheese",
      "eggs",
      "salt",
      "pepper",
      "olive oil",
    ],
    price: 18.0,
  },
  {
    id: 6,
    name: "Thai Red Curry",
    ingredients: [
      "chicken",
      "coconut milk",
      "red curry paste",
      "vegetables",
      "basmati rice",
    ],
    price: 15,
  },
  {
    id: 7,
    name: "Pancakes",
    ingredients: ["flour", "milk", "eggs", "sugar", "baking powder"],
    price: 5,
  },
  {
    id: 8,
    name: "Salmon with Roasted Vegetables",
    ingredients: ["salmon fillets", "olive oil", "vegetables", "lemon", "dill"],
    price: 20,
  },
  {
    id: 9,
    name: "Beef Stir-Fry",
    ingredients: [
      "beef sirloin",
      "vegetables",
      "soy sauce",
      "ginger",
      "noodles",
    ],
    price: 12,
  },
];

export default recipes;
